# Matrix operations for machine learning

![matrixes](https://images.unsplash.com/photo-1573512443418-c6768862dda7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1074&q=80)


photo by [Derek Mckinney](https://unsplash.com/@derickray) at [Unsplash](https://unsplash.com/)


## Introduction

this is the companion colab code for my tutorial in medium about matrix operation introduction in Python , please read the article for better understanding of the code.  
this is a colab notebook, you can test in colab (all the code has been tested and you do not need to set your machine)

[article](https://)



note: the articles will be publish soon

In [2]:
import numpy as np

In [3]:
#matrix
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A)

[[1 2]
 [3 4]]


In [5]:
#slice of matrix
#a row
print(A[1,:])
#a column
print(A[:,1])

[3 4]
[2 4]


In [7]:
#addition
C= A + B
C

array([[ 6,  8],
       [10, 12]])

In [8]:
#subtraction
C= A - B
C

array([[-4, -4],
       [-4, -4]])

In [40]:
#hadamard product, element-wise
C= A * B
C

array([[ 5., 12.],
       [21., 32.]])

In [11]:
#dot product
#you can also use np.dot()
C= A @ B
C

array([[19, 22],
       [43, 50]])

In [15]:
#transpose of a matrix
A_T = A.T
A_T

array([[1, 3],
       [2, 4]])

In [13]:
#identity matrix 
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [18]:
#inverse of a matrix
inv_A = np.linalg.inv(A)
inv_A

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [30]:
#A * inv_A = I
#let's check if it is equal to the identity matrix
np.allclose(np.dot(inv_A, A), np.eye(2))

True

In [34]:
#matrix division
A.dot(np.linalg.inv(B))

array([[ 3., -2.],
       [ 2., -1.]])

In [36]:
#linear equation for x
b= [0.5, 2]
x = np.linalg.inv(A).dot(b)
x

array([ 1.  , -0.25])

In [38]:
#linear equation for X
X = B.dot(np.linalg.inv(A))
X

array([[-1.,  2.],
       [-2.,  3.]])