# Tensors with PyTorch

here the code on how to generate tensor with PyTorch. In this notebook there is also the code about tensor operation with PyTorch. For the theory and other information I will provide a medium article

In [ ]:
import numpy as np
import torch

In [ ]:
x = np.array(7)
y = np.array([1, 3, 5, 7])
z = np.array([[1, 3, 5, 7], [9, 11, 13, 15]])
w = np.array([[[1, 3, 5, 7], [9, 11, 13, 15]], [[1, 3, 5, 7], [9, 11, 13, 15]], [[1, 3, 5, 7], [9, 11, 13, 15]]])
print(f" x rank: {x.ndim}, shape: {x.shape}, data type: {x.dtype} " )
print(f" y rank: {y.ndim}, shape: {y.shape}, data type: {y.dtype} " )
print(f" z rank: {z.ndim}, shape: {z.shape}, data type: {z.dtype} " )
print(f" w rank: {w.ndim}, shape: {w.shape}, data type: {w.dtype} " )

 x rank: 0, shape: (), data type: int64 
 y rank: 1, shape: (4,), data type: int64 
 z rank: 2, shape: (2, 4), data type: int64 
 w rank: 3, shape: (3, 2, 4), data type: int64 


In [ ]:
#you can create tensor of different datatype specifying it
x = torch.tensor(7, dtype=torch.float32)
y = torch.tensor(7, dtype=torch.int32)
x, y

(tensor(7.), tensor(7, dtype=torch.int32))

In [ ]:
#tensor of different rank and shape.
#they are equivalent to the same structures obtained by numpy
x = torch.tensor(7)
y = torch.tensor([1, 3, 5, 7])
z = torch.tensor([[1, 3, 5, 7], [9, 11, 13, 15]])
w = torch.tensor([[[1, 3, 5, 7], [9, 11, 13, 15]], [[1, 3, 5, 7], [9, 11, 13, 15]], [[1, 3, 5, 7], [9, 11, 13, 15]]])
x, y, z, w

(tensor(7), tensor([1, 3, 5, 7]), tensor([[ 1,  3,  5,  7],
         [ 9, 11, 13, 15]]), tensor([[[ 1,  3,  5,  7],
          [ 9, 11, 13, 15]],
 
         [[ 1,  3,  5,  7],
          [ 9, 11, 13, 15]],
 
         [[ 1,  3,  5,  7],
          [ 9, 11, 13, 15]]]))

In [ ]:
#you can check the property:
x = torch.tensor([[1,2,3],[4,5,6]])
print(f" x rank: {x.ndim}, shape: {x.size()}, data type: {x.dtype}, total sum of element: {x.sum()}, is a tensor:{torch.is_tensor(x)} " )


 x rank: 2, shape: torch.Size([2, 3]), data type: torch.int64, total sum of element: 21, is a tensor:True 


In [ ]:
#creating tensor
#from numpy array
z = np.array([[1, 3, 5, 7], [9, 11, 13, 15]])
torch.as_tensor(z), torch.from_numpy(z)
#with range (working like range )
torch.arange(1,5,1)
#with all zeroes or 1
torch.zeros(size = [2,2]), torch.ones(size = [2,2])
#get the same shape of another element, but filled with zeroes or 1
x = torch.arange(1,5,1)
torch.zeros_like(x), torch.ones_like(x)

(tensor([0, 0, 0, 0]), tensor([1, 1, 1, 1]))

## Tensor operation
* addition
* subtraction
* dot product
* Hadamand product (multiplication element wise)

In [ ]:
#operation with tensors:
x = torch.tensor([[1,2], [3,4]], dtype=torch.int64)
y = torch.tensor([[5,6], [7,8]], dtype=torch.int64)
# * is for the dot product, @ for the element wise product
print(x + y)
print(x - y)
print(x @ y)
print(x * y)


tensor([[ 6,  8],
        [10, 12]])
tensor([[-4, -4],
        [-4, -4]])
tensor([[19, 22],
        [43, 50]])
tensor([[ 5, 12],
        [21, 32]])


In [ ]:
#you can obtain the same results also in this way, using the tensor method 
#but you can also call the torch function
x.add(y), torch.add(x,y)
x.subtract(y), torch.subtract(x,y)
x.multiply(y), torch.multiply(x, y)
x.matmul(y), torch.matmul(x, y)

(tensor([[19, 22],
         [43, 50]]), tensor([[19, 22],
         [43, 50]]))

In [ ]:
#broadcasting
x = torch.tensor([[1,2], [3,4], [5,6]], dtype=torch.int64)
y = torch.tensor([5,10], dtype=torch.int64)
x + y

tensor([[ 6, 12],
        [ 8, 14],
        [10, 16]])

In [ ]:
#tensor reshape
x = torch.tensor([[1,2], [3,4], [5,6]], dtype=torch.int64)
#you can do in two way
x.reshape([2,3]), torch.reshape(x, [2,3])
print(x.reshape([2,3]))
#eliminating a dimension
print(x.reshape([-1]))

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([1, 2, 3, 4, 5, 6])


In [ ]:
#transpose
x = torch.tensor([[1,2], [3,4], [5,6]], dtype=torch.int64)
#you can do in this way
torch.t(x)
#or like this, but you have to specify the dimension to be transposed
torch.transpose(x, 0, 1)

tensor([[1, 3, 5],
        [2, 4, 6]])