# Tensors with Tensorflow

here the code on how to generate tensor with tensorflow. In this notebook there is also the code about tensor operation with tensorflow. For the theory and other information I will provide a medium article

In [ ]:
import numpy as np
import tensorflow as tf

In [ ]:
#create array with numpy of different dimension
x = np.array(7)
y = np.array([1, 3, 5, 7])
z = np.array([[1, 3, 5, 7], [9, 11, 13, 15]])
w = np.array([[[1, 3, 5, 7], [9, 11, 13, 15]], [[1, 3, 5, 7], [9, 11, 13, 15]], [[1, 3, 5, 7], [9, 11, 13, 15]]])
print(f" x rank: {x.ndim}, shape: {x.shape}, data type: {x.dtype} " )
print(f" y rank: {y.ndim}, shape: {y.shape}, data type: {y.dtype} " )
print(f" z rank: {z.ndim}, shape: {z.shape}, data type: {z.dtype} " )
print(f" w rank: {w.ndim}, shape: {w.shape}, data type: {w.dtype} " )

 x rank: 0, shape: (), data type: int64 
 y rank: 1, shape: (4,), data type: int64 
 z rank: 2, shape: (2, 4), data type: int64 
 w rank: 3, shape: (3, 2, 4), data type: int64 


In [ ]:
#create tensors with tensorflow, notice the differen size and shape
x = tf.constant(7, dtype=tf.int64)
y = tf.constant([1, 3, 5, 7], dtype=tf.int64)
z = tf.constant([[1, 3, 5, 7], [9, 11, 13, 15]], dtype=tf.int64)
w = tf.constant([[[1, 3, 5, 7], [9, 11, 13, 15]], [[1, 3, 5, 7], [9, 11, 13, 15]], [[1, 3, 5, 7], [9, 11, 13, 15]]], dtype=tf.int64)
print(x), print(y), print(z), print(w), 

tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor([1 3 5 7], shape=(4,), dtype=int64)
tf.Tensor(
[[ 1  3  5  7]
 [ 9 11 13 15]], shape=(2, 4), dtype=int64)
tf.Tensor(
[[[ 1  3  5  7]
  [ 9 11 13 15]]

 [[ 1  3  5  7]
  [ 9 11 13 15]]

 [[ 1  3  5  7]
  [ 9 11 13 15]]], shape=(3, 2, 4), dtype=int64)


(None, None, None, None)

In [ ]:
#alternative way about creating a shape, you can provide the list of number and the relative shape
x = tf.constant(7, dtype=tf.int64)
y = tf.constant([1, 3, 5, 7], shape = [1,4],  dtype=tf.int64)
z = tf.constant([1, 3, 5, 7, 9, 11, 13, 15], shape = [2,4], dtype=tf.int64)
x, y, z

(<tf.Tensor: shape=(), dtype=int64, numpy=7>,
 <tf.Tensor: shape=(1, 4), dtype=int64, numpy=array([[1, 3, 5, 7]])>,
 <tf.Tensor: shape=(2, 4), dtype=int64, numpy=
 array([[ 1,  3,  5,  7],
        [ 9, 11, 13, 15]])>)

## Tensor operation
* addition
* subtraction
* dot product
* Hadamand product (multiplication element wise)


In [ ]:
x = tf.constant([1,2,3,4], shape = [2,2], dtype=tf.int64)
y = tf.constant([5,6,7,8], shape = [2,2],  dtype=tf.int64)

In [ ]:
#notice that * is for the dot product and @ is for element wise product
x + y, x * y, x @ y

(<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
 array([[ 6,  8],
        [10, 12]])>, <tf.Tensor: shape=(2, 2), dtype=int64, numpy=
 array([[ 5, 12],
        [21, 32]])>, <tf.Tensor: shape=(2, 2), dtype=int64, numpy=
 array([[19, 22],
        [43, 50]])>)

In [ ]:
#multiply is the element wise product
#matmul is for the dot product
tf.add(x, y), tf.multiply(x,y), tf.matmul(x,y)

(<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
 array([[ 6,  8],
        [10, 12]])>, <tf.Tensor: shape=(2, 2), dtype=int64, numpy=
 array([[ 5, 12],
        [21, 32]])>, <tf.Tensor: shape=(2, 2), dtype=int64, numpy=
 array([[19, 22],
        [43, 50]])>)

## Reshaping, transposing and broadcasting

In [ ]:
#broadcasting
x = tf.constant([1,2,3,4,5,6], shape = [3,2], dtype=tf.int64 )
z = tf.constant([5,10], dtype=tf.int64 )
x + z

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[ 6, 12],
       [ 8, 14],
       [10, 16]])>

In [ ]:
#notice as we change the shape of the tensor
x, tf.reshape(x, [2,3])

(<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>, <tf.Tensor: shape=(2, 3), dtype=int64, numpy=
 array([[1, 2, 3],
        [4, 5, 6]])>)

In [ ]:
#transpose of a matrix
x, tf.transpose(x)

(<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>, <tf.Tensor: shape=(2, 3), dtype=int64, numpy=
 array([[1, 3, 5],
        [2, 4, 6]])>)